name: Deploy

on:  
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.GITHUB_TOKEN}}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |        
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements.txt
        python -m pip install ghp-import
    - name: Create website
      run: |        
        pelican content
        ghp-import output
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
