name: Deploy

on:  
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |        
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements.txt
    - name: Create website
      run: |
        git checkout -b gh-pages        
        pelican content
        git add -f output
        git commit -m "Deploy website update"        
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
